# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aea49c36f27e28430a86f32f9f1cbe1a99612e92be60ac41107addcf4ec62d9c3d1583fac3e5df8c6378a581dacd38b1fb0cae9e90047dc1e921b46daf2892c

test:
  secret_key_base: ec778831e7c07370e83b091d5813051fc13e6eaf66c9888cbdc336429ecc6a30f9d487fb4a45a60c847d1af4f3b875c8e0affb0948bdb7ec9d700bb6bc0fda9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
